name: release please action

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: terraform-module
          package-name: ${{env.ACTION_NAME}}
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Add tags to PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = process.env.PR_NUMBER;
            github.rest.git.createRef({
              owner: github.repository_owner,
              repo: github.repository,
              ref: `refs/tags/pr-${prNumber}`,
              sha: github.sha
            });
        env:
          PR_NUMBER: ${{ github.event.number }}