name: Release Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      upload_url: ${{ steps.release.outputs.upload_url }}
      labels: ${{ steps.release.outputs.labels }}
    steps:
      - name: Release Please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: terraform-module
          package-name: ${{ env.ACTION_NAME }}

      - name: tag major and patch versions
        if: "steps.release.outputs.labels && contains(steps.release.outputs.labels, 'autorelease: pending')"
        run: |
          echo "Running step because autorelease: pending label is present "

      - name: tag major and patch versions
        if: "steps.release.outputs.labels && contains(steps.release.outputs.labels, 'autorelease: tagged')"
        run: |
          echo "Running step because autorelease: tagged label is present"
