# Terraform Provider testing workflow.
name: resource development branch tests

# This GitHub action runs your tests for each pull request and push.
# Optionally, you can turn it on using a schedule for regular testing.
on:
  push:
    branches-ignore:
      - main
      - development
    paths-ignore:
      - 'README.md'

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

jobs:
  # Check test results and fail the workflow if the tests fail.
  intergration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check test result
        run: |
          changed_files=$(git diff --name-only HEAD $(git merge-base HEAD))
          test_function=$(grep -E '^func TestAcc.*\(t \*testing.T\)' $changed_files | awk -F 'func ' '{print $2}' | awk -F '(' '{print $1}')
          if [[ -n "$test_function" ]]; then
            # Run the test and store the output in a variable
            test_output=$(go test -v -cover -run "$test_function" ./internal/provider/ 2>&1)
            # Check if the test passed by searching for a specific pattern in the output
            if echo "$test_output" | grep -q "PASS"; then
              echo "TestAcc Passed"
            else
              echo "TestAcc Failed"
              exit 1
            fi
          else
            echo "TestAcc function not found"
          fi